import { Injectable } from '@angular/core';
import { SupabaseService } from './supabase.service';
import { Island } from '../models';

@Injectable({
    providedIn: 'root'
})
export class IslandService {
    constructor(private supabase: SupabaseService) { }

    async getAll() {
        return await this.supabase
            .from('islands')
            .select('*')
            .order('name');
    }

    async getById(id: string) {
        return await this.supabase
            .from('islands')
            .select('*')
            .eq('id', id)
            .single();
    }

    async create(island: Partial<Island>) {
        // Token is auto-generated by database
        return await this.supabase
            .from('islands')
            .insert(island)
            .select()
            .single();
    }

    async update(id: string, island: Partial<Island>) {
        return await this.supabase
            .from('islands')
            .update(island)
            .eq('id', id)
            .select()
            .single();
    }

    async delete(id: string) {
        return await this.supabase
            .from('islands')
            .delete()
            .eq('id', id);
    }

    async toggleStatus(id: string, status: 'active' | 'inactive') {
        return await this.update(id, { status });
    }

    async regenerateToken(id: string) {
        // Generate new UUID token
        const newToken = crypto.randomUUID();
        return await this.update(id, { token: newToken });
    }
}
